# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  (1..3).each do |i|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.

    localhost = "127.0.0.1"

    # Provision three RKE2 nodes (1 server, 2 agents)
    config.vm.define "rke2-node-#{i}" do |node|
      node.vm.box = "bento/ubuntu-22.04"
      node.vm.network "private_network", ip: "192.168.33.10#{i}"

      # View the documentation for the provider you are using for more
      # information on available options.

      # Libvirt part
      node.vm.provider :libvirt do |libvirt|
        libvirt.driver = "kvm"
        libvirt.cpu_model = "EPYC-Rome"
        libvirt.cpus = 2
        libvirt.memory = 4096
        libvirt.storage_pool_name = "kvm"
        libvirt.storage :file, :size => '40G'
      end

      # Classic 80/443 ports
      node.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: localhost
      node.vm.network "forwarded_port", guest: 443, host: 8443, host_ip: localhost

      # Install some tools
      node.vm.provision "shell", inline: <<-SHELL
        apt-get update
        apt-get install apt-transport-https ca-certificates curl btop htop git unzip wget curl -y
        sudo snap install helm --classic && sudo snap install kubectl --classic
      SHELL

      # RKE2 ports
      node.vm.network "forwarded_port", guest: 9345, host: 9345, host_ip: localhost
      node.vm.network "forwarded_port", guest: 6443, host: 6443, host_ip: localhost
      (2379...2382).each do |port|
        node.vm.network "forwarded_port", guest: port, host: port, host_ip: localhost
      end
      node.vm.network "forwarded_port", guest: 10250, host: 10250, host_ip: localhost
      node.vm.network "forwarded_port", guest: 10257, host: 10257, host_ip: localhost
      node.vm.network "forwarded_port", guest: 10259, host: 10259, host_ip: localhost

      # Folder sync
      node.vm.synced_folder ".", "/vagrant", type: "nfs", nfs_version: 4, nfs_udp: false

      # Enable provisioning with a shell script. Additional provisioners such as
      # Ansible, Chef, Docker, Puppet and Salt are also available. Please see the
      # documentation for more information about their specific syntax and use.
      if i == 1
        node.vm.provision "shell", inline: <<-SHELL

          # Install RKE2 server
          curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="server" sh -

          # Start RKE2 server
          systemctl enable rke2-server.service
          systemctl start rke2-server.service

          # Write the token to a file
          mkdir -p /vagrant
          cat /var/lib/rancher/rke2/server/node-token > /vagrant/node-token

          cp /etc/rancher/rke2/rke2.yaml /vagrant/kubeconfig.yaml

          # Set the KUBECONFIG environment variable for all users
          echo "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml" >> /etc/profile.d/kubeconfig.sh
          echo "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml" >> /home/vagrant/.bashrc

          echo '1' > /vagrant/node1_ready
        SHELL
      else
        node.vm.provision "shell", inline: <<-SHELL
          # Wait until Node 1 is ready
          while [ ! -f /vagrant/node1_ready ]; do sleep 1; done

          # Install RKE2 agent
          curl -sfL https://get.rke2.io | INSTALL_RKE2_TYPE="agent" sh -

          # Point RKE2 agent to the server
          sudo mkdir -p /etc/rancher/rke2/
          sudo echo "server: https://192.168.33.101:9345" >> /etc/rancher/rke2/config.yaml
          sudo echo "token: $(cat /vagrant/node-token)" >> /etc/rancher/rke2/config.yaml

          # Prepare RKE2 agent
          systemctl enable rke2-agent.service

          # Start RKE2 agent
          systemctl start rke2-agent.service

          # Set the KUBECONFIG environment variable for all users
          echo "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml" >> /etc/profile.d/kubeconfig.sh
          echo "export KUBECONFIG=/etc/rancher/rke2/rke2.yaml" >> /home/vagrant/.bashrc


          echo '1' > /vagrant/node#{i}_ready
        SHELL
      end

      # Unblock Kubernetes NodePort range (30000-32767)
      # This can take a while in the background
      # (30000...32767).each do |port|
      #   node.vm.network "forwarded_port", guest: port, host: port, host_ip: "127.0.0.1"
      # end
    end
  end
end
